### ISSUE TITLE
sys: fails to find xcb/xcb_cursor.h under non-default prefix

### ISSUE THREAD

**Issue by jbeich** [JuliusKreutz/xcb-util-cursor-rs#1]
Affects [FreeBSD](https://wiki.freebsd.org/WarnerLosh/UsrLocal#Include_paths), other BSDs and maybe even Nix due to using different prefix for each package. To reproduce install `xcb-util-cursor` outside of `/usr` and `/usr/local` thus not part of default C compiler search path.

```
$ cargo build
[...]
error: failed to run custom build command for `xcb-util-cursor-sys v0.1.3 (/tmp/xcb-util-cursor-rs/xcb-util-cursor-sys)`

Caused by:
  process didn't exit successfully: `/tmp/xcb-util-cursor-rs/target/debug/build/xcb-util-cursor-sys-358522a50fa03efc/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=xcb-cursor
  cargo:rerun-if-changed=wrapper.h

  --- stderr
  wrapper.h:1:10: fatal error: 'xcb/xcb_cursor.h' file not found
  thread 'main' panicked at xcb-util-cursor-sys/build.rs:13:10:
  Unable to generate bindings: ClangDiagnostic("wrapper.h:1:10: fatal error: 'xcb/xcb_cursor.h' file not found\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

$ pkg-config --cflags xcb-cursor
-I/xcb-cursor_prefix/include
```

**Comment by juliuskreutz** [comment]
Hi! Thank you for bringing this up.

The [new version](https://crates.io/crates/xcb-util-cursor) now uses pkg-config to add the correct include paths when building xcb-util-cursor-sys.

Could you report back, if that fixed your issue?

**Comment by jbeich** [comment]
I confirm, builds fine now. Also tested [downstream](https://github.com/freebsd/freebsd-ports/commit/94d5f5d859e7).
